name: Check Changelog

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'api/**'
      - 'ui/**'
      - 'prowler/**'

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get list of changed files
        id: changed_files
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff --name-only origin/${{ github.base_ref }}...HEAD > changed_files.txt
          cat changed_files.txt

      - name: Check for folder changes and changelog presence
        id: check_folders
        run: |
          missing_changelogs=""

          for folder in api ui prowler; do
            if grep -q "^${folder}/" changed_files.txt; then
              echo "Detected changes in ${folder}/"
              if ! grep -q "^${folder}/CHANGELOG.md$" changed_files.txt; then
                echo "No changelog update found for ${folder}/"
                missing_changelogs="${missing_changelogs}${folder} "
              fi
            fi
          done

          echo "missing_changelogs=${missing_changelogs}" >> $GITHUB_OUTPUT

      - name: Comment on PR if changelog is missing
        if: steps.check_folders.outputs.missing_changelogs != ''
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ⚠️ **Changes detected in the following folders that have not been updated in your CHANGELOG.md**:
            ${{ steps.check_folders.outputs.missing_changelogs }}

            Please add an entry to the corresponding `CHANGELOG.md` to maintain a clear history of changes.
