name: Test - Merged Pull Request

on:
  pull_request_target:
    branches: ['main']
    types: ['closed']

jobs:
  trigger-cloud-pull-request:
    name: Trigger Cloud Pull Request
    if: github.event.pull_request.merged == true && github.repository == 'prowler-cloud/test-actions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set short git commit SHA
        id: vars
        run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "SHORT_SHA=${shortSha}" >> $GITHUB_ENV

      - name: Trigger pull request
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.PROWLER_BOT_ACCESS_TOKEN }}
          repository: "prowler-cloud/test-actions-dispatched"
          event-type: test-pull-request-merged
          client-payload: '{
            "TEST_COMMIT_SHA": "${{ github.sha }}",
            "TEST_COMMIT_SHORT_SHA": "${{ env.SHORT_SHA }}",
            "TEST_PR_TITLE": "${{ github.event.pull_request.title }}",
            "TEST_PR_LABELS": ${{ toJson(github.event.pull_request.labels.*.name) }},
            "TEST_PR_BODY": ${{ toJson(github.event.pull_request.body) }}
          }'
