name: Test - Push, Release, Manual dispatch

on:
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/push-release-manual-dispatch.yml
  release:
    types: [published]
  workflow_dispatch:

jobs:
  first-job:
    if: github.event_name == 'push' || github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - run: |
          echo "First job"
  second-job:
    if: always()
    runs-on: ubuntu-latest
    needs: first-job
    permissions:
      id-token: write
      contents: read
    steps:
      - run: |
          echo "Second job"
  third-job:
    runs-on: ubuntu-latest
    needs: second-job
    if: github.event_name != 'workflow_dispatch' || needs.second-job.result == 'success'
    permissions:
      id-token: write
      contents: read
    steps:
      - run: |
          echo "Third job"
