name: SDK - Bump Version

on:
  release:
    types: [published]

env:
  RELEASE_TAG: ${{ github.event.release.tag_name }}
  
jobs:
  bump-version:
    name: Bump Version
    if: github.repository == 'prowler-cloud/test-actions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Prowler version
        run: |
          PROWLER_VERSION="${{ env.RELEASE_TAG }}"

          if [[ $PROWLER_VERSION =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            MAJOR_VERSION=${BASH_REMATCH[1]}
            MINOR_VERSION=${BASH_REMATCH[2]}
            FIX_VERSION=${BASH_REMATCH[3]}

            if (( MAJOR_VERSION == 5 )); then
                if (( FIX_VERSION == 0 )); then
                  echo "Minor Release: $PROWLER_VERSION"
                  echo "TARGET_BRANCH=master" >> ${GITHUB_ENV}
                  echo "BUMP_VERSION_TO=${MAJOR_VERSION}.$((MINOR_VERSION + 1)).${FIX_VERSION}" >> ${GITHUB_ENV}
                else
                  echo "Fix/Bug Release: $PROWLER_VERSION"
                  echo "TARGET_BRANCH=v${MAJOR_VERSION}.${MINOR_VERSION}" >> ${GITHUB_ENV}
                  echo "BUMP_VERSION_TO=${MAJOR_VERSION}.${MINOR_VERSION}.$((FIX_VERSION + 1))" >> ${GITHUB_ENV}
                fi
            else
                echo "Releasing another Prowler major version, aborting..."
                exit 1
            fi
          else
            echo "Invalid version syntax: '$PROWLER_VERSION' (must be N.N.N)" >&2
            exit 1
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
            author: prowler-bot <179230569+prowler-bot@users.noreply.github.com>
            token: ${{ secrets.PROWLER_BOT_ACCESS_TOKEN }}
            commit-message: "chore(release): Bump version to v${{ env.BUMP_VERSION_TO }}"
            branch: "version-bump-to-v${{ env.BUMP_VERSION_TO }}"
            title: "chore(release): Bump version to v${{ env.BUMP_VERSION_TO }}"
            body: |
              ### Description

              Bump Prowler version to v${{ env.BUMP_VERSION_TO }}.

              ### License

              By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
