name: Workflow Parent

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/workflow-parent.yml'
      - 'workflow-parent/**'

jobs:
  workflow-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Hello World
        run:
          echo hello-world.txt