name: Workflow Child

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/workflow-child.yml'
      - 'workflow-child/**'

  workflow_run:
    workflows:
      - 'Workflow Parent'
    types:
      - completed

jobs:
  workflow-child:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Hello World
        run:
          echo hello-world.txt